/*This file was generated by NativeWind. Do not edit!*/
const {NativeWindStyleSheet: _NativeWindStyleSheet} = require('nativewind');
_NativeWindStyleSheet.create({
  styles: {
    '*': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    '': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    html: {
      lineHeight: 1.5,
      fontFamily: 'ui-sans-serif',
    },
    body: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    hr: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    'abbr:where([title])': {
      textDecorationLine: 'underline',
      textDecorationColor: 'black',
      textDecorationStyle: 'dotted',
    },
    code: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    kbd: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    samp: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    pre: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    small: {
      fontSize: '80%',
    },
    sub: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    sup: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    button: {
      backgroundColor: 'transparent',
    },
    input: {
      opacity: 1,
      color: '#9ca3af',
    },
    optgroup: {
      fontFamily: 'inherit',
      fontSize: '100%',
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    select: {
      width: '100%',
    },
    textarea: {
      width: '100%',
    },
    "[type='button']": {
      backgroundColor: 'transparent',
    },
    "[type='reset']": {
      backgroundColor: 'transparent',
    },
    "[type='submit']": {
      backgroundColor: 'transparent',
    },
    ':-moz-ui-invalid': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'black',
      shadowOpacity: 1,
    },
    blockquote: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dl: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dd: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h1: {
      fontSize: 36,
      lineHeight: 40,
    },
    h2: {
      fontSize: 30,
      lineHeight: 36,
    },
    h3: {
      fontSize: 24,
      lineHeight: 32,
    },
    h4: {
      fontSize: 20,
      lineHeight: 28,
    },
    h5: {
      fontSize: 18,
      lineHeight: 28,
    },
    h6: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    figure: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    p: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    fieldset: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    legend: {
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ol: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ul: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    menu: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    img: {
      maxWidth: '100%',
    },
    video: {
      maxWidth: '100%',
    },
    '[hidden]': {
      display: 'none',
    },
    a: {
      textDecorationLine: 'underline',
    },
    "[type='text']": {
      width: '100%',
    },
    "[type='email']": {
      width: '100%',
    },
    "[type='url']": {
      width: '100%',
    },
    "[type='password']": {
      width: '100%',
    },
    "[type='number']": {
      width: '100%',
    },
    "[type='date']": {
      width: '100%',
    },
    "[type='datetime-local']": {
      width: '100%',
    },
    "[type='month']": {
      width: '100%',
    },
    "[type='search']": {
      width: '100%',
    },
    "[type='tel']": {
      width: '100%',
    },
    "[type='time']": {
      width: '100%',
    },
    "[type='week']": {
      width: '100%',
    },
    '[multiple]': {
      width: '100%',
    },
    "[type='text']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='email']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='url']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='password']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='number']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='date']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='datetime-local']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='month']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='search']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='tel']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='time']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='week']@0": {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    '[multiple]@0': {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    'textarea@0': {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    'select@0': {
      elevation: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
    },
    "[type='text']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='email']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='url']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='password']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='number']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='date']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='datetime-local']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='month']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='search']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='tel']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='time']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='week']@1": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    '[multiple]@1': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    'textarea@1': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    'select@1': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='text']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='email']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='url']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='password']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='number']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='date']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='datetime-local']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='month']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='search']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='tel']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='time']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    "[type='week']@2": {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    '[multiple]@2': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    'textarea@2': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    'select@2': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'rgba(0, 0, 0, 0)',
      shadowOpacity: 1,
    },
    btn: {
      borderTopWidth: 2,
      borderRightWidth: 2,
      borderBottomWidth: 2,
      borderLeftWidth: 2,
      fontWeight: '700',
    },
    'btn:disabled': {
      opacity: 0.4,
    },
    'btn.btn-small': {
      paddingTop: 10,
      paddingBottom: 10,
    },
    'btn.btn-medium': {
      paddingTop: 10,
      paddingBottom: 10,
    },
    'btn.btn-large': {
      paddingTop: 12,
      paddingBottom: 12,
    },
    'mb-2': {
      marginBottom: 8,
    },
    'h-[60px]': {
      height: 60,
    },
    'h-full': {
      height: '100%',
    },
    'flex-1': {
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: '0%',
    },
    'flex-row': {
      flexDirection: 'row',
    },
    'items-center': {
      alignItems: 'center',
    },
    'justify-center': {
      justifyContent: 'center',
    },
    'bg-[#fff]': {
      backgroundColor: '#fff',
    },
    'p-3': {
      paddingTop: 12,
      paddingRight: 12,
      paddingBottom: 12,
      paddingLeft: 12,
    },
    'font-black': {
      fontWeight: '900',
    },
    'gap-3': {
      marginLeft: -12,
      marginTop: -12,
    },
    'gap-3.children@0': {
      marginLeft: 12,
      marginTop: 12,
    },
  },
  atRules: {
    "[type='text']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='email']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='url']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='password']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='number']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='date']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='datetime-local']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='month']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='search']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='tel']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='time']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    "[type='week']": [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    '[multiple]': [
      [['media', 'android']],
      [['media', 'ios']],
      [['media', 'web']],
    ],
    textarea: [[['media', 'android']], [['media', 'ios']], [['media', 'web']]],
    select: [[['media', 'android']], [['media', 'ios']], [['media', 'web']]],
    'gap-3.children': [[['selector', '(> *)']]],
  },
  masks: {
    "[type='text']": 512,
    "[type='email']": 512,
    "[type='url']": 512,
    "[type='password']": 512,
    "[type='number']": 512,
    "[type='date']": 512,
    "[type='datetime-local']": 512,
    "[type='month']": 512,
    "[type='search']": 512,
    "[type='tel']": 512,
    "[type='time']": 512,
    "[type='week']": 512,
    '[multiple]': 512,
    textarea: 512,
    select: 512,
  },
  childClasses: {
    'gap-3': ['gap-3.children'],
  },
});
