/*This file was generated by NativeWind. Do not edit!*/
const {
  NativeWindStyleSheet: _NativeWindStyleSheet
} = require("nativewind");
_NativeWindStyleSheet.create({
  styles: {
    "*": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "": {
      "borderTopWidth": 0,
      "borderRightWidth": 0,
      "borderBottomWidth": 0,
      "borderLeftWidth": 0,
      "borderStyle": "solid",
      "borderTopColor": "#e5e7eb",
      "borderRightColor": "#e5e7eb",
      "borderBottomColor": "#e5e7eb",
      "borderLeftColor": "#e5e7eb"
    },
    "html": {
      "lineHeight": 1.5,
      "fontFamily": "ui-sans-serif"
    },
    "body": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "hr": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "abbr:where([title])": {
      "textDecorationLine": "underline",
      "textDecorationColor": "black",
      "textDecorationStyle": "dotted"
    },
    "code": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "kbd": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "samp": {
      "fontFamily": "ui-monospace",
      "fontSize": "1em"
    },
    "pre": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "small": {
      "fontSize": "80%"
    },
    "sub": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "sup": {
      "fontSize": "75%",
      "lineHeight": 0,
      "position": "relative"
    },
    "button": {
      "backgroundColor": "transparent"
    },
    "input": {
      "opacity": 1,
      "color": "#9ca3af"
    },
    "optgroup": {
      "fontFamily": "inherit",
      "fontSize": "100%",
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "select": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "textarea": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='button']": {
      "backgroundColor": "transparent"
    },
    "[type='reset']": {
      "backgroundColor": "transparent"
    },
    "[type='submit']": {
      "backgroundColor": "transparent"
    },
    ":-moz-ui-invalid": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "black",
      "shadowOpacity": 1
    },
    "blockquote": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dl": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "dd": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "h1": {
      "fontSize": 36,
      "lineHeight": 40
    },
    "h2": {
      "fontSize": 30,
      "lineHeight": 36
    },
    "h3": {
      "fontSize": 24,
      "lineHeight": 32
    },
    "h4": {
      "fontSize": 20,
      "lineHeight": 28
    },
    "h5": {
      "fontSize": 18,
      "lineHeight": 28
    },
    "h6": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "figure": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "p": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0
    },
    "fieldset": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "legend": {
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ol": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "ul": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "menu": {
      "marginTop": 0,
      "marginRight": 0,
      "marginBottom": 0,
      "marginLeft": 0,
      "paddingTop": 0,
      "paddingRight": 0,
      "paddingBottom": 0,
      "paddingLeft": 0
    },
    "img": {
      "maxWidth": "100%"
    },
    "video": {
      "maxWidth": "100%"
    },
    "[hidden]": {
      "display": "none"
    },
    "a": {
      "textDecorationLine": "underline"
    },
    "[type='text']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='email']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='url']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='password']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='number']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='date']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='datetime-local']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='month']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='search']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='tel']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='time']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='week']": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[multiple]": {
      "borderTopLeftRadius": "0.325em",
      "borderTopRightRadius": "0.325em",
      "borderBottomRightRadius": "0.325em",
      "borderBottomLeftRadius": "0.325em"
    },
    "[type='text']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='email']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='url']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='password']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='number']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='date']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='datetime-local']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='month']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='search']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='tel']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='time']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='week']@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[multiple]@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "textarea@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "select@0": {
      "elevation": 0,
      "shadowColor": "rgba(0, 0, 0, 0)"
    },
    "[type='text']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='email']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='url']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='password']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='number']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='date']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='datetime-local']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='month']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='search']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='tel']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='time']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='week']@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[multiple]@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "textarea@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "select@1": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='text']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='email']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='url']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='password']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='number']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='date']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='datetime-local']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='month']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='search']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='tel']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='time']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='week']@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[multiple]@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "textarea@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "select@2": {
      "shadowOffset": {
        "width": 0,
        "height": 0
      },
      "shadowRadius": 0,
      "shadowColor": "rgba(0, 0, 0, 0)",
      "shadowOpacity": 1
    },
    "[type='checkbox']": {
      "borderTopColor": "#f73911",
      "borderRightColor": "#f73911",
      "borderBottomColor": "#f73911",
      "borderLeftColor": "#f73911",
      "color": "#f73911"
    },
    "[type='radio']": {
      "borderTopColor": "#f73911",
      "borderRightColor": "#f73911",
      "borderBottomColor": "#f73911",
      "borderLeftColor": "#f73911",
      "color": "#f73911"
    },
    "[type='checkbox'].hasSuccess": {
      "color": "#4cad6e"
    },
    "[type='radio'].hasSuccess": {
      "color": "#4cad6e"
    },
    "[type='checkbox'].hasWarning": {
      "color": "#ffb830"
    },
    "[type='radio'].hasWarning": {
      "color": "#ffb830"
    },
    "[type='checkbox'].hasError": {
      "color": "#f2686e"
    },
    "[type='radio'].hasError": {
      "color": "#f2686e"
    },
    "btn": {
      "borderTopWidth": 2,
      "borderRightWidth": 2,
      "borderBottomWidth": 2,
      "borderLeftWidth": 2,
      "fontWeight": "700"
    },
    "btn:disabled": {
      "opacity": 0.4
    },
    "btn.btn-primary": {
      "color": "#fff"
    },
    "btn.btn-secondary": {
      "color": "#fff"
    },
    "btn.btn-success": {
      "color": "#000"
    },
    "btn.btn-danger": {
      "color": "#000"
    },
    "btn.btn-warning": {
      "color": "#000"
    },
    "btn.btn-small": {
      "paddingTop": 10,
      "paddingBottom": 10
    },
    "btn.btn-medium": {
      "paddingTop": 10,
      "paddingBottom": 10
    },
    "btn.btn-large": {
      "paddingTop": 12,
      "paddingBottom": 12
    },
    "font-black": {
      "fontWeight": "900"
    },
    "text-primary": {
      "color": "#f73911"
    }
  },
  atRules: {
    "[type='text']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='email']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='url']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='password']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='number']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='date']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='datetime-local']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='month']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='search']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='tel']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='time']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[type='week']": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "[multiple]": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "textarea": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]],
    "select": [[["media", "android"]], [["media", "ios"]], [["media", "web"]]]
  },
  masks: {
    "[type='text']": 512,
    "[type='email']": 512,
    "[type='url']": 512,
    "[type='password']": 512,
    "[type='number']": 512,
    "[type='date']": 512,
    "[type='datetime-local']": 512,
    "[type='month']": 512,
    "[type='search']": 512,
    "[type='tel']": 512,
    "[type='time']": 512,
    "[type='week']": 512,
    "[multiple]": 512,
    "textarea": 512,
    "select": 512
  }
});